services:
  app:
    build: .
    restart: on-failure
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql://root:root@db:3306/prisma?connection_limit=10
    depends_on:
      - db
      - redis
    command: >
      sh -c "npx prisma migrate deploy && npx prisma generate && npm start"

  db:
    image: mysql:8.0
    container_name: mysqldatabase
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: prisma
    ports:
      - '3307:3306'
    volumes:
      - mysql:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  mysql:
